### ISSUE TITLE
add index.html template for the resume

### ISSUE THREAD

**Issue by TrissMerigolt** [TrissMerigolt/my-resume#1]
!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Résumé</title>
  </head>
  <body>
    ― Hello World! &#x1F609;
  </body>
</html>

**Comment by MridulTi** [comment]
Ok I will add the template to your resume, just tell me what you would like to see there

**Comment by MridulTi** [comment]
I added the tempelate and all you can check the pull request for that
